# Generated by Django 5.2.3 on 2025-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='url_picture',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
