# Generated by Django 5.2.3 on 2025-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_user_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url_picture',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
